name = "rklib"
author = "Jacob Williams"
copyright  = "Copyright (c) 2022-2023, Jacob Williams"
license = "BSD-3"
description = "Fixed and variable-step Runge-Kutta solvers in Modern Fortran"
homepage = "https://github.com/jacobwilliams/rklib"
keywords = ["ode"]

[build]
auto-executables = false
auto-examples = false
auto-tests = true

[dependencies]
roots-fortran = { git = "https://github.com/jacobwilliams/roots-fortran", rev = "1.1.0" }

[library]
source-dir = "src"

[install]
library = true